
/******************************************************************************
 DO NOT EDIT - This file is generated by the SysConfig tool.
 @file config.h

 @brief TI-15.4 Stack feature parameters definitions for sensor applications

 Group: WCS LPC
 $Target Device: DEVICES $

 ******************************************************************************
 $License: BSD3 2016 $
 ******************************************************************************
 $Release Name: PACKAGE NAME $
 $Release Date: PACKAGE RELEASE DATE $
 *****************************************************************************/
#ifndef FEATURES_H
#define FEATURES_H

#ifdef __cplusplus
extern "C"
{
#endif

/* Builds the image with the mac layer security turned on */
#define FEATURE_MAC_SECURITY

/* Builds the image with nonBeacon mode of operation */
#define FEATURE_NON_BEACON_MODE


#ifdef __cplusplus
}
#endif

#endif /* FEATURES_H */
