/******************************************************************************
 DO NOT EDIT - This file is generated by the SysConfig tool.
 @file config.h

 @brief TI-15.4 Stack configuration parameters for Sensor applications

 Group: WCS LPC
 $Target Device: DEVICES $

 ******************************************************************************
 $License: BSD3 2016 $
 ******************************************************************************
 $Release Name: PACKAGE NAME $
 $Release Date: PACKAGE RELEASE DATE $
 *****************************************************************************/
#ifndef CONFIG_H
#define CONFIG_H

/******************************************************************************
 Includes
 *****************************************************************************/
#include "api_mac.h"
#include "features.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define CONFIG_FH_ENABLE    false

#define CONFIG_SECURE true     
#define CONFIG_PAN_ID 0xFFFF     
#define CONFIG_MAX_DATA_FAILURES 5     
/* Unused CONFIG_FH_MAX_ASSOCIATION_ATTEMPTS generated for code compilation */
#define CONFIG_FH_MAX_ASSOCIATION_ATTEMPTS 3     
#define CONFIG_SCAN_BACKOFF_INTERVAL 5000     
#define CONFIG_ORPHAN_BACKOFF_INTERVAL 300000     
#define CONFIG_PHY_ID APIMAC_PHY_ID_NONE     
#define CONFIG_MIN_BE 3     
#define CONFIG_MAX_BE 5     
#define CONFIG_MAC_MAX_CSMA_BACKOFFS 5     
#define CONFIG_MAX_RETRIES 5     
#define CONFIG_CHANNEL_PAGE APIMAC_CHANNEL_PAGE_NONE     
#define CONFIG_SCAN_DURATION 5     
/* Unused FH_COORD_SHORT_ADDR generated for code compilation */
#define FH_COORD_SHORT_ADDR 0xAABB     

#define KEY_TABLE_DEFAULT_KEY { 0x12,0x34,0x56,0x78,0x9A,0xBC,0xDE,0xF0, \
                   0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 }

#define CONFIG_CHANNEL_MASK    { 0x00,0x78,0x00,0x00,0x00,0x00, \
                          0x00,0x00,0x00,0x00,0x00,0x00, \
                         0x00,0x00,0x00,0x00,0x00 }

/* Unused CONFIG_FH_CHANNEL_MASK generated for code compilation */
#define CONFIG_FH_CHANNEL_MASK    { 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF, \
                          0xFF,0x00,0x00,0x00,0x00,0x00, \
                         0x00,0x00,0x00,0x00,0x00 }

/* Unused FH_ASYNC_CHANNEL_MASK generated for code compilation */
#define FH_ASYNC_CHANNEL_MASK    { 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF, \
                          0xFF,0xFF,0xFF,0xFF,0xFF,0xFF, \
                         0xFF,0xFF,0xFF,0xFF,0xFF }

#define CONFIG_RX_ON_IDLE false     
/* Unused FH_NUM_NON_SLEEPY_HOPPING_NEIGHBORS generated for code compilation */
#define FH_NUM_NON_SLEEPY_HOPPING_NEIGHBORS 5     
/* Unused FH_NUM_NON_SLEEPY_FIXED_CHANNEL_NEIGHBORS generated for code compilation */
#define FH_NUM_NON_SLEEPY_FIXED_CHANNEL_NEIGHBORS 5     
/* Unused CONFIG_DWELL_TIME generated for code compilation */
#define CONFIG_DWELL_TIME 250     
#define CONFIG_POLLING_INTERVAL 2000     
/* Unused CONFIG_PAN_ADVERT_SOLICIT_CLK_DURATION generated for code compilation */
#define CONFIG_PAN_ADVERT_SOLICIT_CLK_DURATION 6000     
/* Unused CONFIG_PAN_CONFIG_SOLICIT_CLK_DURATION generated for code compilation */
#define CONFIG_PAN_CONFIG_SOLICIT_CLK_DURATION 6000     
#define CONFIG_REPORTING_INTERVAL 3000     
/* Unused CONFIG_FH_START_POLL_DATA_RAND_WINDOW generated for code compilation */
#define CONFIG_FH_START_POLL_DATA_RAND_WINDOW 10000     
#define SENSOR_TEST_RAMP_DATA_SIZE 0     
/* Unused CONFIG_FH_NETNAME generated for code compilation */
#define CONFIG_FH_NETNAME {"FHTest"}     
#define CONFIG_TRANSMIT_POWER 0     
#define CONFIG_MAC_BEACON_ORDER 15     
#define CONFIG_MAC_SUPERFRAME_ORDER 15     
/* Unused FH_BROADCAST_INTERVAL generated for code compilation */
#define FH_BROADCAST_INTERVAL 10000     
/* Unused FH_BROADCAST_DWELL_TIME generated for code compilation */
#define FH_BROADCAST_DWELL_TIME 100     
/* Unused CONFIG_TRICKLE_MIN_CLK_DURATION generated for code compilation */
#define CONFIG_TRICKLE_MIN_CLK_DURATION 3000     
/* Unused CONFIG_TRICKLE_MAX_CLK_DURATION generated for code compilation */
#define CONFIG_TRICKLE_MAX_CLK_DURATION 6000     
/* Unused CONFIG_DOUBLE_TRICKLE_TIMER generated for code compilation */
#define CONFIG_DOUBLE_TRICKLE_TIMER false     
#define CERTIFICATION_TEST_MODE false     
#define POWER_TEST_PROFILE DATA_ACK     

#ifdef __cplusplus
}
#endif

#endif /* CONFIG_H */
